<template>
  <div>
    <b-row class="icontainer-subpage">
      <b-col>
        <div class="ftitle">Terms Of Service</div>
        <div class="fpublishtime">Last Updated: April 16, 2022</div>
        <div class="fcontain">
          <div class="fsubtitle">Introduction</div>
          <p>Welcome to Openpublish software and services!</p>
          <p>In order to use the Openpublish Software and Services, you must carefully read and fully understand the content of each provision of this Agreement, especially the provisions that exclude or limit liability, and the separate agreement to open or use a particular service, and choose to accept or not to accept it. Restrictions and exclusions of liability may be brought to your attention in bolded form, etc.</p>
          <p>These Terms of Service ("Terms") govern your access to and use of the Openpublish website, mobile applications ("Apps"), and any software, tools or features available on them, in connection with our Services. including, without limitation, using our Services to view, create NFTs and publish NFTs; including, without limitation, using our Services to view, purchase, stake or transfer OPH tokens on the public blockchains; including, without limitation, using our tools to contact others directly to buy, sell or transfer NFTs & OPH on the public blockchains at your own discretion (collectively, the "Services"). "NFTs&OPH" in these Terms means non-fungible tokens implemented on a blockchain (such as the Ether blockchain) and ERC20 equity token issued by OpenPublish.</p>
          <p>In these Terms, "User," "you" and "your" refer to you as a user of the Services. If you are using the Services on behalf of a company or other entity then "you" includes both you and that entity, and you represent and warrant that (a) you are an authorized representative of that entity and have the authority to bind that entity to these Terms, and (b) you agree to these Terms on behalf of the entity.</p>
          <p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION AND AFFECT YOUR LEGAL RIGHTS.BY CLICKING TO ACCEPT AND/OR USING OUR SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE SERVICE.</p>
          <p>We sometimes need to provide additional terms for specific services (such services are considered part of the "Services" under this Agreement and shall also be subject to these terms). If you use these Services, these additional terms and conditions will become part of your agreement with us, and these terms and conditions will apply to the relevant Services. To the extent that these terms conflict with any other applicable terms we may provide for a particular Service, such additional terms shall apply to that particular Service.</p>
          <p>OpenPublish reserves the right to change or modify these Terms at any time and in our sole discretion. If we make material changes to these Terms, we will use reasonable efforts to provide notice of such changes, such as by providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference effective as of the date these Terms are updated. It is your sole responsibility to review the Terms from time to time to view such changes and to ensure that you understand the terms and conditions that apply when you access or use the Service.</p>

          <div class="fsubtitle">Accessing the Service</div>
          <p>OpenPublish is not a wallet provider, exchange, broker, financial institution, or creditor. OpenPublish provides a peer-to-peer web3 service that helps users discover and directly interact with each other and NFTs&OPH available on public blockchains. To use our Service, you must use a third-party wallet which allows you to engage in transactions on blockchains.</p>
          <p>Your blockchain address serves as your identity in OpenPublish. Therefore, you will need a blockchain address and a third-party wallet to access the Service by associating your account on the Service ("Account") with your blockchain address.</p>
          <p>Your Account on OpenPublish will be associated with your linked blockchain address and display the NFTs&OPH for that blockchain address (and, if applicable, any content associated with such NFTs&OPH). By using your wallet in connection with the Service, you agree that you are using that wallet under the terms and conditions of the applicable provider of the wallet. Wallets are not operated by, maintained by, or affiliated with OpenPublish, and OpenPublish does not have custody or control over the contents of your wallet and has no ability to retrieve or transfer its contents. OpenPublish accepts no responsibility for, or liability to you, in connection with your use of a wallet and makes no representations or warranties regarding how the Service will operate with any specific wallet. You are solely responsible for keeping your wallet secure and you should never share your wallet credentials or seed phrase with anyone. If you discover an issue related to your wallet, please contact your wallet provider. Likewise, you are solely responsible for your Account and any associated wallet and we are not liable for any acts or omissions by you in connection with your Account or as a result of your Account or wallet being compromised. You agree to immediately notify us if you discover or otherwise suspect any security issues related to the Service or your Account (you can contact us <a class="f-p-serive" href="https://discord.gg/tKMbjCdVYf" target="_blank">here</a>).</p>
          <p>You represent and warrant that you will comply with all applicable laws when using the Services. The OpenPublish project is a fully public trading platform for NFTs built on the blockchain. We will conduct our business and offer NFTs&OPH to the right people in a legal manner and in strict compliance with the laws and regulations of each country and region of the world, and citizens or groups of people in any country with legal restrictions will not be allowed to participate in the public or private sale of NFTs&OPH in the Open Publish Project.</p>

          <p>You also represent and warrant that: (a) you are not located in a country that is subject to a U.S. Government embargo; and (b) you have not been identified as a Specially Designated National or placed on any U.S. Government list of prohibited, sanctioned, or restricted parties. If you access or use the Service outside the United States, you are solely responsible for ensuring that your access and use of the Service in such country, territory or jurisdiction does not violate any applicable laws.</p>
          <p>OpenPublish may require you to provide additional information and documents in certain circumstances, such as at the request of any government authority, as any applicable law or regulation dictates, or to investigate a potential violation of these Terms. In such cases, OpenPublish, in its sole discretion, may disable your Account and block your ability to access the Service until such additional information and documents are processed by OpenPublish. If you do not provide complete and accurate information in response to such a request, OpenPublish may refuse to restore your access to the Service.</p>
          <p>Your access and use of the Service may be interrupted from time to time for any of several reasons, including, without limitation, the malfunction of equipment, periodic updating, maintenance, or repair of the Service or other actions that OpenPublish, in its sole discretion, may elect to take.</p>
          <p>We require all users to be at least 18 years old. If you are at least 13 years old but under 18 years old, you may only use OpenPublish through a parent or guardian’s Account and with their approval and oversight. That account holder is responsible for your actions using the Account. It is prohibited to use our Service if you are under 13 years old.</p>
          <p>Even so, OpenPublish projects are likely to be questioned and regulated by authorities in different countries around the world. In order to meet and comply with local laws and regulations, the OpenPublish project may not be able to provide normal services in some regions.</p>

          <div class="fsubtitle">Ownership</div>
          <p>The Service, including its “look and feel” (e.g., text, graphics, images, logos, page headers, button icons, and scripts), proprietary content, information and other materials, and all content and other materials contained therein, including, without limitation, the OpenPublish logo and all designs, text, graphics, pictures, data, software, sound files, other files, and the selection and arrangement thereof are the proprietary property of OpenPublish or our affiliates, licensors, or users, as applicable, and you agree not to take any action(s) inconsistent with such ownership interests. We and our affiliates, licensors, and users, as applicable, reserve all rights in connection with the Service and its content, including, without limitation, the exclusive right to create derivative works.</p>
          <p>OpenPublish’s name, logo, trademarks, and any OpenPublish product or service names, designs, logos, and slogans are the intellectual property of OpenPublish or our affiliates or licensors and may not be copied, imitated or used, in whole or in part, without our prior written permission in each instance. You may not use any metatags or other “hidden text” utilizing “OpenPublish” or any other name, trademark or product or service name of OpenPublish or our affiliates or licensors without our prior written permission. In addition, the “look and feel” of the Service constitutes the service mark, trademark or trade dress of OpenPublish and may not be copied, imitated or used, in whole or in part, without our prior written permission.</p>
          <p>All other third-party trademarks, registered trademarks, and product names mentioned on the Service or contained in the content linked to or associated with any NFTs&OPH displayed on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable intellectual property rights holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship, or recommendation by OpenPublish.</p>
          <p>We welcome feedback, comments, and suggestions for improvements to the Service (“Feedback”). You acknowledge and expressly agree that any contribution of Feedback does not and will not give or grant you any right, title, or interest in the Service or in any such Feedback. You agree that OpenPublish may use and disclose Feedback in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to OpenPublish any and all right, title, and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback.</p>

          <div class="fsubtitle">License to Access and Use Our Service and Content</div>
          <p>You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service provided, however, that such license is subject to your compliance with these Terms. If any software, content, or other materials owned by, controlled by, or licensed to us are distributed or made available to you as part of your use of the Service, we hereby grant you a non-commercial, personal, non-assignable, non-sublicensable, non-transferrable, and non-exclusive right and license to access and display such software, content, and materials provided to you as part of the Service (and right to download a single copy of the App onto your applicable equipment or device), in each case for the sole purpose of enabling you to use the Service as permitted by these Terms, provided that your license in any content linked to or associated with any NFTs is solely as set forth by the applicable seller or creator of such NFT.</p>

          <div class="fsubtitle">User Conduct</div>
          <p>Anyone's use of the Services is based on compliance with the law. In order to protect our community and comply with our legal obligations, we reserve the right to take action, with or without prior notice, if we believe that you have violated these Terms. This may include: disabling your ability to access our Services; removing your ability to view or transact on the Services / or other actions.</p>
          <p>You agree that you will not violate any law, contract, intellectual property or other third-party right, and that you are solely responsible for your conduct and content, while accessing or using the Service. You also agree that you will not:</p>
          <p>Use or attempt to use another user’s Account without authorization from such user;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Pose as another person or entity;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Claim an OpenPublish username for the purpose of reselling it or otherwise engage in name squatting;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Access the Service from a different blockchain address if we’ve blocked any of your other blockchain addresses from accessing the Service, unless you have our written permission first;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Distribute spam, including through sending unwanted NFTs to other users;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service – including through disseminating any software or interacting with any API – that could damage, disable, overburden, or impair the functioning of the Service in any manner;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Bypass or ignore instructions that control access to the Service, including attempting to circumvent any rate limiting systems by using multiple API keys, directing traffic through multiple IP addresses, or otherwise obfuscating the source of traffic you send to OpenPublish;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use any data mining, robot, spider, crawler, scraper, script, browser extension, offline reader, or other automated means or interface not authorized by us to access the Service, extract data, or otherwise interfere with or modify the rendering of Service pages or functionality;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Reverse engineer, duplicate, decompile, disassemble, or decode any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any service, area, or code of the Service;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon>	Sell or resell the Service or attempt to circumvent any OpenPublish fee systems;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Engage in behaviors that have the intention or the effect of artificially causing an item or collection to appear at the top of search results, or artificially increasing view counts, favorites, or other metrics that OpenPublish might use to sort search results;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service or data collected from our Service for any advertising or direct marketing activity (including without limitation, email marketing, SMS marketing, and telemarketing);</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service for money laundering, terrorist financing, or other illicit finance;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service from a country sanctioned by the government of the United States or to facilitate transactions involving individuals sanctioned by the government of the United States or located in sanctioned countries;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, selling, or buying securities, commodities, options, or debt instruments;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service to create, sell, or buy NFTs&OPH or other items that give owners rights to participate in an ICO or any securities offering, or that are redeemable for securities, commodities, or other financial instruments;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service to engage in price manipulation, fraud, or other deceptive, misleading, or manipulative activity;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service to buy, sell, or transfer stolen items, fraudulently obtained items, items taken without authorization, and/or any other illegally obtained items;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Infringe or violate the intellectual property rights or any other rights of others;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Create or display illegal content, such as content that may involve child sexual exploitation;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Create or display NFTs or other items that promote suicide or self-harm, incites hate or violence against others, or doxes another individual;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service for any illegal or unauthorized purpose, including creating or displaying illegal content, such as content that may involve child sexual exploitation, or encouraging or promoting any activity that violates the Terms of Service;</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service.</p>


          <div class="fsubtitle">Intellectual Property Rights</div>
          <p>You are solely responsible for your use of the Service and for any information you provide, including compliance with applicable laws, rules, and regulations, as well as these Terms, including the User Conduct requirements outlined above. YOU REPRESENT AND WARRANT THAT YOU OWN OR HAVE BEEN GRANTED ALL RIGHTS, CONSENTS, POWERS OR AUTHORIZATIONS TO ENSURE THAT YOU HAVE ALL THE RIGHTS TO ENSURE THE LEGALITY OF YOUR ACTIONS IN CREATING, SUBMITTING, PUBLISHING, PROMOTING OR DISPLAYING YOUR CONTENT ON OPENPUBLISH.</p>
          <p>By using the Service in conjunction with creating, submitting, posting, promoting, or displaying content, or by complying with OpenPublish metadata standards in your metadata API responses, you grant us a worldwide, non-exclusive, sublicensable, royalty-free license to use, copy, modify, and display any content, including but not limited to text, materials, images, files, communications, comments, feedback, suggestions, ideas, concepts, questions, data, or otherwise, that you submit or post on or through the Service for our current and future business purposes, including to provide, promote, and improve the Service. This includes any digital file, art, or other material linked to or associated with any NFTs that are displayed on the Service.</p>
          <p>OpenPublish does not claim that submitting, posting, or displaying this content on or through the Service gives OpenPublish any ownership of the content. We're not saying we own it. We're just saying we might use it and show it off a bit.</p>
          <p>You represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for any content that you create, submit, post, promote, or display on or through the Service. You represent and warrant that such content does not contain material subject to copyright, trademark, publicity rights, or other intellectual property rights, unless you have necessary permission or are otherwise legally entitled to post the material and to grant OpenPublish the license described above, and that the content does not violate any laws.</p>
          <p>OpenPublish will take down works in response to Digital Millennium Copyright Act (“DMCA”) takedown notices and/or other intellectual property infringement claims and will terminate a user's access to the Service if the user is determined to be a repeat infringer. If you believe that your content has been copied in a way that constitutes copyright or trademark infringement, or violates your publicity or other intellectual property rights, please fill out our form  <a class="f-p-serive" href="https://discord.gg/tKMbjCdVYf" target="_blank">here</a>).</p>


          <div class="fsubtitle">Communication Preferences</div>
          <p>By creating an Account, you consent to receive electronic communications from OpenPublish (e.g., via email, push notification, text messages, or other types of messages). These communications may include notices about your Account (e.g., transactional information) and are part of your relationship with us. We may also send you promotional communications via email we think will be of interest to you. You understand that you are not required to provide this consent as a condition of using the Service and you may opt out of these communications through the Service or through your mobile device’s operating system (with the possible exception of important service announcements and administrative messages) by following the unsubscribe instructions provided.</p>


          <div class="fsubtitle">Indemnification</div>
          <p>By agreeing to these Terms and accessing the Service, you agree, to the fullest extent permitted by applicable law, to indemnify, defend, and hold harmless OpenPublish, and our respective past, present, and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors, and assigns (individually and collectively, the “OpenPublish Parties”), from and against all actual or alleged claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses), and costs (including, without limitation, court costs, costs of settlement, and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract, or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, content, NFTs&OPH, or content linked to or associated with any NFTs (b) any Feedback you provide, (c) your violation or breach of any term of these Terms or applicable law, and (d) your violation of the rights of or obligations to a third party, including another user or third-party, and (e) your negligence or wilful misconduct. You agree to promptly notify OpenPublish of any Claims and cooperate with the OpenPublish Parties in defending such Claims. You further agree that the OpenPublish Parties shall have control of the defense or settlement of any Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND OPENPUBLISH.</p>

          <div class="fsubtitle">Disclaimers</div>
          <p>YOUR ACCESS TO AND USE OF THE SERVICE IS AT YOUR OWN RISK. YOU UNDERSTAND AND AGREE THAT THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND OPENPUBLISH EXPRESSLY DISCLAIMS WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. OPENPUBLISH (AND ITS SUPPLIERS) MAKE NO WARRANTY OR REPRESENTATION AND DISCLAIM ALL RESPONSIBILITY FOR WHETHER THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. OPENPUBLISH DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. OPENPUBLISH WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE.</p>
          <p>WHILE OPENPUBLISH ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE SAFE, OPENPUBLISH CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, CONTENT LINKED TO OR ASSOCIATED WITH ANY NFTS&OPH, OR ANY NFTS&OPH YOU INTERACT WITH USING OUR SERVICE OR OUR SERVICE PROVIDERS’ SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. NO ADVICE OR INFORMATION, WHETHER ORAL OR OBTAINED FROM THE OPENPUBLISH PARTIES OR THROUGH THE SERVICE, WILL CREATE ANY WARRANTY OR REPRESENTATION NOT EXPRESSLY MADE HEREIN. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD OPENPUBLISH RESPONSIBLE FOR ANY BREACH OF SECURITY.</p>
          <p>WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF NFTS&OPH, CONTENT, AND/OR CONTENT LINKED TO OR ASSOCIATED WITH NFTS&OPH, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES, OR CLAIMS ARISING FROM: (A) THE USER HAS LEAKED, LOST OR DESTROYED THE WALLET PRIVATE KEY OF NFT & OPH. (B) USER ERROR, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (C) SERVER FAILURE OR DATA LOSS; (D) UNAUTHORIZED ACCESS OR USE; (E) ANY UNAUTHORIZED THIRD-PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR NFTS&OPH (F) ANY LOSSES CAUSED BY USERS' TRADING OR SPECULATION ON NFT & OPH; (G) LISTING, SUSPENSION OR DELISTING OF NFTS & OPH ON ANY TRADING PLATFORM; AN AUTHORITY OR PUBLIC BODY CLASSIFIES OR TREATS AS A CURRENCY, SECURITY, COMMERCIAL PAPER, NEGOTIABLE INSTRUMENT, INVESTMENT OR OTHER THING SO THAT IT IS PROHIBITED, REGULATED OR RESTRICTED BY LAW.</p>
          <p>ANY TRANSFERS OR SALES OCCUR ON THE ASSOCIATED BLOCKCHAIN (E.G., ETHEREUM). OPENPUBLISH AND/OR ANY OTHER OPENPUBLISH PARTY CANNOT EFFECT OR OTHERWISE CONTROL THE TRANSFER OF TITLE OR RIGHT IN ANY NFTS&OPH OR UNDERLYING OR ASSOCIATED CONTENT OR ITEMS.</p>
          <p>NO OPENPUBLISH PARTY IS RESPONSIBLE OR LIABLE FOR ANY SUSTAINED LOSSES OR INJURY DUE TO VULNERABILITY OR ANY KIND OF FAILURE, ABNORMAL BEHAVIOR OF SOFTWARE (E.G., WALLET, SMART CONTRACT), BLOCKCHAINS OR ANY OTHER FEATURES OF THE NFTS&OPH. INCLUDING BUT NOT LIMITED TO (A) DEVELOPMENT FAILURE OR ABANDONMENT OF THE OPENPUBLSIH PROJECT AND THE RESULTING FAILURE TO DELIVER OR THE INABILITY TO USE NFTS & OPH.(B) ERRORS, DEFECTS, FLAWS, OR OTHER PROBLEMS WITH THE OPENPUBLISH PROJECT AND ITS NFTS & OPH SOURCE CODE. (C) FAILURES, CRASHES, OUTAGES, ROLLBACKS OR HARD FORKS OF THE OPENPUBLISH PROJECT PLATFORM, NFTS & OPH. (D) FAILURE OF THE OPENPUBLISH PROJECT OR NFTS & OPH TO IMPLEMENT ANY SPECIFIC FUNCTIONALITY OR SUITABILITY FOR ANY SPECIFIC PURPOSE. (E) FOR LOSSES OR INJURY DUE TO LATE REPORTS BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN SUPPORTING THE NFTS, INCLUDING FORKS, TECHNICAL NODE ISSUES OR ANY OTHER ISSUES HAVING LOSSES OR INJURY AS A RESULT.</p>
          <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>
          <p>You accept and acknowledge:</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> The value of an NFTs&OPH is subjective. Prices of NFTs&OPH are subject to volatility and fluctuations in the price of cryptocurrency can also materially and adversely affect NFTs&OPH prices. You acknowledge that you fully understand this subjectivity and volatility and that you may lose money.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility of NFTs&OPH.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> The regulatory regime governing blockchain technologies, non-fungible tokens, cryptocurrency, and other crypto-based items is uncertain, and new regulations or policies may materially adversely affect the development of the Service and the utility of NFTs&OPH.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> You are solely responsible for determining what, if any, taxes apply to your transactions. OpenPublish is not responsible for determining the taxes that apply to your NFTs&OPH.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> There are risks associated with purchasing items associated with content created by third parties through peer-to-peer transactions, including but not limited to, the risk of purchasing counterfeit items, mislabeled items, items that are vulnerable to metadata decay, items on smart contracts with bugs, and items that may become untransferable. You represent and warrant that you have done sufficient research before making any decisions to sell, obtain, transfer, or otherwise interact with any NFTs&OPH or accounts/collections.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> We do not control the public blockchains that you are interacting with and we do not control certain smart contracts and protocols that may be integral to your ability to complete transactions on these public blockchains. Additionally, blockchain transactions are irreversible and OpenPublish has no ability to reverse any transactions on the blockchain.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> There are risks associated with using Internet and blockchain based products, including, but not limited to, the risk associated with hardware, software, and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to your third-party wallet or Account. You accept and acknowledge that OpenPublish will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Service or any Blockchain network, however caused.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> The Service relies on third-party platforms and/or vendors. If we are unable to maintain a good relationship with such platform providers and/or vendors; if the terms and conditions or pricing of such platform providers and/or vendors change; if we violate or cannot comply with the terms and conditions of such platforms and/or vendors; or if any of such platforms and/or vendors loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> OpenPublish reserves the right to hide collections, contracts, and items affected by any of these issues or by other issues. Items you purchase may become inaccessible on OpenPublish. Under no circumstances shall the inability to view items on OpenPublish or an inability to use the Service in conjunction with the purchase, sale, or transfer of items available on any blockchains serve as grounds for a claim against OpenPublish.</p>
          <p><b-icon icon="circle-fill" font-scale="0.9"></b-icon> If you have a dispute with one or more users, you release us from claims, demands, and damages of every kind and nature, known and unknown, arising out of or in any way connected with such disputes. In entering into this release you expressly waive any protections (whether statutory or otherwise) that would otherwise limit the coverage of this release to include those claims which you may know or suspect to exist in your favor at the time of agreeing to this release.</p>



          <div class="fsubtitle">Limitation of Liability</div>
          <p>TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AGREE THAT IN NO EVENT WILL OPENPUBLISH OR ITS SERVICE PROVIDERS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES ARISING FROM THESE TERMS OR THE SERVICE, PRODUCTS OR THIRD-PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF OPENPUBLISH OR ITS SERVICE PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (B) FOR ANY OTHER CLAIM, DEMAND, OR DAMAGES WHATSOEVER RESULTING FROM OR ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF THE DELIVERY, USE, OR PERFORMANCE OF THE SERVICE. ACCESS TO, AND USE OF, THE SERVICE, PRODUCTS OR THIRD-PARTY SITES, AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.</p>
          <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF OPENPUBLISH ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, NFTS, OR ANY OPENPUBLISH PRODUCTS OR SERVICES EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY OPENPUBLISH FOR ITS SERVICE DIRECTLY RELATING TO THE ITEMS THAT ARE THE SUBJECT OF THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
          <p>Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.</p>

          <div class="fsubtitle">Privacy Policy</div>
          <p>Please refer to our Privacy Policy for information about how we collect, use, and share personal data about you. By submitting personal data through our Service, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use, and disclosure of your personal data in accordance with the Privacy Policy.</p>

          <div class="fsubtitle">Modifications to the Service</div>
          <p>We reserve the right in our sole discretion to modify, suspend, or discontinue, temporarily or permanently, the Service (or any features or parts thereof) at any time and without liability as a result.</p>

          <div class="fsubtitle">Termination</div>
          <p>If you breach any of the provisions of these Terms, all licenses granted by OpenPublish will terminate automatically. Additionally, notwithstanding anything contained in these Terms, we reserve the right, with or without notice and in our sole discretion, to suspend, disable, terminate, or delete your Account and/or your ability to access or use the Service (or any part of the foregoing) at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us.</p>

          <div class="fsubtitle">Severability</div>
          <p>If any term, clause, or provision of these Terms is held invalid or unenforceable, then that term, clause, or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause, or provision, or any other term, clause, or provision of these Terms.</p>


          <div class="fsubtitle">Injunctive Relief</div>
          <p>You agree that a breach of these Terms will cause irreparable injury to OpenPublish for which monetary damages would not be an adequate remedy and OpenPublish shall be entitled to equitable relief in addition to any remedies it may have hereunder or at law without a bond, other security, or proof of damages.</p>


          <div class="fsubtitle">Survival</div>
          <p>All sections which by their nature should survive the termination of these Terms shall continue in full force and effect subsequent to and notwithstanding any termination of these Terms by OpenPublish or you. Termination will not limit any of OpenPublish’s other rights or remedies at law or in equity.</p>


          <div class="fsubtitle">Miscellaneous</div>
          <p>These Terms constitute the entire agreement between you and OpenPublish relating to your access to and use of the Service. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of OpenPublish, and OpenPublish’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for reference only and shall not be read to have any legal effect.</p>
          <p>The Service is operated by us in the United States. Those who choose to access the Service from locations outside the United States do so at their own initiative and are responsible for compliance with applicable local laws. You and OpenPublish agree that the United Nations Convention on Contracts for the International Sale of Goods will not apply to the interpretation or construction of these Terms.</p>
          <p>Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties and are not intended to confer third-party beneficiary rights upon any other person or entity.</p>
          <p></p>
          <p></p>



        </div>

      </b-col>
    </b-row>
  </div>
</template>

<script>
  export default {
    name:'userservice'
  }
</script>

<style scoped="scoped">
  @import url("../../assets/scss/com.css");
  .ftitle{
    width: 100%;
    line-height: 7.2rem;
    font-size: 2.56rem;
    font-weight: 600;
  }
  .fpublishtime{
    width: 100%;
    line-height: 2.56rem;
  }
  .fcontain{
    width: 100%;
    font-weight: 500 ;
  }
  .fcontain .fsubtitle{
    font-size: 1.44rem;
    margin: 1rem 0 0.5rem;
  }
  .fcontain > p{
    font-weight: 400;
  }
  .fcontain > p .f-p-serive{
    font-weight: 500;
    font-size: 1.44rem;
    color: #5152BD;
  }
</style>
